### ISSUE TITLE
[Suggestion] Using libwacom

### ISSUE THREAD

**Issue by Banbeucmas** [hawku/TabletDriver#149]
I am not that familiar with C++ related production. But I notice there is this
https://github.com/linuxwacom/libwacom

Could we use this to integrate with the driver as it would help a lot?.

**Comment by hawku** [comment]
Libwacom is the library part of the Linux Wacom driver, so that can't be used with this driver.

I'm already using the data from the Linux Wacom kernel driver:
https://github.com/hawku/TabletDriver/blob/master/TabletDriverService/config/wacom.cfg

The Linux kernel driver code isn't very modular and would be almost impossible to fully convert that to Windows C++ code.
