### ISSUE TITLE
VirusTotal detections

### ISSUE THREAD

**Issue by Foreme** [hawku/TabletDriver#256]
Just noticed a couple detections in VirusTotal, wanted to bring it up before I continue using.

https://www.virustotal.com/#/file/c8c67ed7999091f5b25c6aed2d4c6bc1235d2379bfacd432f6cf050b75f1e839/detection

**Comment by hawku** [comment]
I think that some false positive virus detections are to be excepted.
The driver is reading data from USB devices and simulates mouse movements, so that might trigger the antivirus software to detect it as a virus or a trojan. 

If you don't trust the compiled binary, you can compile the source code by yourself.

**Comment by Foreme** [comment]
All good, just wanted to make sure this is normal. Thank you for the reply!
